#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AppIncidencias.Resource", IsApplication=true)]

namespace AppIncidencias
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int tipousuarios = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int EditTextApellidos = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int EditTextEmail = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int EditTextNick = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int EditTextNombre = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int EditTextPassword = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int EditTextTelefono = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int SpinnerTipoUsuarios = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int TextViewApellidos = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int TextViewEmail = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int TextViewNick = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int TextViewNombre = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int TextViewPassword = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int TextViewTelefono = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int TextViewTitle = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int buttonRegistro = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int linearInterior = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Registro = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
