#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AppIncidencias.Resource", IsApplication=true)]

namespace AppIncidencias
{


	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{

		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}

		public static void UpdateIdValues()
		{
		}

		public partial class Array
		{

			// aapt resource value: 0x7f050000
			public const int tipousuarios = 2131034112;

			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Array()
			{
			}
		}

		public partial class Attribute
		{

			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Attribute()
			{
			}
		}

		public partial class Drawable
		{

			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;

			// aapt resource value: 0x7f020001
			public const int location = 2130837505;

			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Drawable()
			{
			}
		}

		public partial class Id
		{


			// aapt resource value: 0x7f06003a
			public const int EditTextApellidos = 2131099706;

			// aapt resource value: 0x7f06003c
			public const int EditTextEmail = 2131099708;

			// aapt resource value: 0x7f060032
			public const int EditTextNick = 2131099698;

			// aapt resource value: 0x7f060038
			public const int EditTextNombre = 2131099704;

			// aapt resource value: 0x7f060034
			public const int EditTextPassword = 2131099700;

			// aapt resource value: 0x7f06003e
			public const int EditTextTelefono = 2131099710;

			// aapt resource value: 0x7f06003f
			public const int SpinnerTipoUsuarios = 2131099711;

			// aapt resource value: 0x7f060039
			public const int TextViewApellidos = 2131099705;

			// aapt resource value: 0x7f060009
			public const int TextViewDetalleHabitacion = 2131099657;

			// aapt resource value: 0x7f060017
			public const int TextViewDetalleMantenimiento = 2131099671;

			// aapt resource value: 0x7f06003b
			public const int TextViewEmail = 2131099707;

			// aapt resource value: 0x7f060004
			public const int TextViewEncargado = 2131099652;

			// aapt resource value: 0x7f060002
			public const int TextViewHabitacion = 2131099650;

			// aapt resource value: 0x7f060006
			public const int TextViewHorario = 2131099654;

			// aapt resource value: 0x7f060028
			public const int TextViewInventarioLimpieza = 2131099688;

			// aapt resource value: 0x7f06002b
			public const int TextViewLimpieza = 2131099691;

			// aapt resource value: 0x7f060031
			public const int TextViewNick = 2131099697;

			// aapt resource value: 0x7f060037
			public const int TextViewNombre = 2131099703;

			// aapt resource value: 0x7f060033
			public const int TextViewPassword = 2131099699;

			// aapt resource value: 0x7f06003d
			public const int TextViewTelefono = 2131099709;

			// aapt resource value: 0x7f060001
			public const int TextViewTitle = 2131099649;

			// aapt resource value: 0x7f060030
			public const int TextViewTitleLogin = 2131099696;

			// aapt resource value: 0x7f06002c
			public const int buttonAnyadirHabitacionLimpieza = 2131099692;

			// aapt resource value: 0x7f060029
			public const int buttonAnyadirInventarioLimpieza = 2131099689;

			// aapt resource value: 0x7f060008
			public const int buttonCrearOrdenLimpieza = 2131099656;

			// aapt resource value: 0x7f060036
			public const int buttonLogin = 2131099702;

			// aapt resource value: 0x7f060040
			public const int buttonRegistro = 2131099712;

			// aapt resource value: 0x7f060007
			public const int datePickerHorarioLimpieza = 2131099655;

			// aapt resource value: 0x7f06001d
			public const int editText1 = 2131099677;

			// aapt resource value: 0x7f060035
			public const int enlaceCredenciales = 2131099701;

			// aapt resource value: 0x7f060021
			public const int imageButton1 = 2131099681;

			// aapt resource value: 0x7f060022
			public const int imageButton2 = 2131099682;

			// aapt resource value: 0x7f060018
			public const int imageViewDetalleMantenimiento = 2131099672;

			// aapt resource value: 0x7f06000a
			public const int imageViewLocationIcon = 2131099658;

			// aapt resource value: 0x7f060019
			public const int imageViewUbicacionDetalleMantenimiento = 2131099673;

			// aapt resource value: 0x7f060016
			public const int linearDetalleMantenimiento = 2131099670;

			// aapt resource value: 0x7f060000
			public const int linearInterior = 2131099648;

			// aapt resource value: 0x7f06002f
			public const int linearLayout1 = 2131099695;

			// aapt resource value: 0x7f06002a
			public const int listViewInventarioLimpieza = 2131099690;

			// aapt resource value: 0x7f06002d
			public const int listViewLimpieza = 2131099693;

			// aapt resource value: 0x7f06002e
			public const int scrollView1 = 2131099694;

			// aapt resource value: 0x7f060015
			public const int scrollViewDetalleMantenimiento = 2131099669;

			// aapt resource value: 0x7f060030
			public const int EditTextApellidos = 2131099696;

			// aapt resource value: 0x7f060032
			public const int EditTextEmail = 2131099698;

			// aapt resource value: 0x7f060028
			public const int EditTextNick = 2131099688;

			// aapt resource value: 0x7f06002e
			public const int EditTextNombre = 2131099694;

			// aapt resource value: 0x7f06002a
			public const int EditTextPassword = 2131099690;

			// aapt resource value: 0x7f060034
			public const int EditTextTelefono = 2131099700;

			// aapt resource value: 0x7f060035
			public const int SpinnerTipoUsuarios = 2131099701;

			// aapt resource value: 0x7f06002f
			public const int TextViewApellidos = 2131099695;

			// aapt resource value: 0x7f060014
			public const int TextViewDetalleHabitacion = 2131099668;

			// aapt resource value: 0x7f060031
			public const int TextViewEmail = 2131099697;

			// aapt resource value: 0x7f060030
			public const int EditTextApellidos = 2131099696;

			// aapt resource value: 0x7f060032
			public const int EditTextEmail = 2131099698;

			// aapt resource value: 0x7f060028
			public const int EditTextNick = 2131099688;

			// aapt resource value: 0x7f06002e
			public const int EditTextNombre = 2131099694;

			// aapt resource value: 0x7f06002a
			public const int EditTextPassword = 2131099690;

			// aapt resource value: 0x7f060034
			public const int EditTextTelefono = 2131099700;

			// aapt resource value: 0x7f060035
			public const int SpinnerTipoUsuarios = 2131099701;

			// aapt resource value: 0x7f06002f
			public const int TextViewApellidos = 2131099695;

			// aapt resource value: 0x7f060014
			public const int TextViewDetalleHabitacion = 2131099668;

			// aapt resource value: 0x7f060031
			public const int TextViewEmail = 2131099697;

			// aapt resource value: 0x7f060004
			public const int TextViewEncargado = 2131099652;

			// aapt resource value: 0x7f060002
			public const int TextViewHabitacion = 2131099650;

			// aapt resource value: 0x7f060006
			public const int TextViewHorario = 2131099654;

			// aapt resource value: 0x7f060020
			public const int TextViewInventarioLimpieza = 2131099680;

			// aapt resource value: 0x7f060023
			public const int TextViewLimpieza = 2131099683;

			// aapt resource value: 0x7f060027
			public const int TextViewNick = 2131099687;

			// aapt resource value: 0x7f06002d
			public const int TextViewNombre = 2131099693;

			// aapt resource value: 0x7f060029
			public const int TextViewPassword = 2131099689;

			// aapt resource value: 0x7f060033
			public const int TextViewTelefono = 2131099699;

			// aapt resource value: 0x7f060001
			public const int TextViewTitle = 2131099649;

			// aapt resource value: 0x7f060026
			public const int TextViewTitleLogin = 2131099686;

			// aapt resource value: 0x7f060024
			public const int buttonAnyadirHabitacionLimpieza = 2131099684;

			// aapt resource value: 0x7f060021
			public const int buttonAnyadirInventarioLimpieza = 2131099681;

			// aapt resource value: 0x7f060008
			public const int buttonCrearOrdenLimpieza = 2131099656;


			// aapt resource value: 0x7f06002c
			public const int buttonLogin = 2131099692;

			// aapt resource value: 0x7f060036
			public const int buttonRegistro = 2131099702;

			// aapt resource value: 0x7f060007
			public const int datePickerHorarioLimpieza = 2131099655;


			// aapt resource value: 0x7f060020
			public const int TextViewInventarioLimpieza = 2131099680;

			// aapt resource value: 0x7f060023
			public const int TextViewLimpieza = 2131099683;

			// aapt resource value: 0x7f060027
			public const int TextViewNick = 2131099687;

			// aapt resource value: 0x7f06002d
			public const int TextViewNombre = 2131099693;

			// aapt resource value: 0x7f060029
			public const int TextViewPassword = 2131099689;

			// aapt resource value: 0x7f060033
			public const int TextViewTelefono = 2131099699;

			// aapt resource value: 0x7f060013
			public const int editText1 = 2131099667;

			// aapt resource value: 0x7f06002b
			public const int enlaceCredenciales = 2131099691;

			// aapt resource value: 0x7f060015
			public const int imageViewLocationIcon = 2131099669;

			// aapt resource value: 0x7f060000
			public const int linearInterior = 2131099648;


			// aapt resource value: 0x7f06000a
			public const int linearLayout1 = 2131099658;


			// aapt resource value: 0x7f060026
			public const int TextViewTitleLogin = 2131099686;

			// aapt resource value: 0x7f060024
			public const int buttonAnyadirHabitacionLimpieza = 2131099684;

			// aapt resource value: 0x7f060021
			public const int buttonAnyadirInventarioLimpieza = 2131099681;

			// aapt resource value: 0x7f060008
			public const int buttonCrearOrdenLimpieza = 2131099656;

			// aapt resource value: 0x7f06002c
			public const int buttonLogin = 2131099692;

			// aapt resource value: 0x7f060036
			public const int buttonRegistro = 2131099702;

			// aapt resource value: 0x7f060022
			public const int listViewInventarioLimpieza = 2131099682;

			// aapt resource value: 0x7f060025
			public const int listViewLimpieza = 2131099685;


			// aapt resource value: 0x7f060009
			public const int scrollView1 = 2131099657;


			// aapt resource value: 0x7f060013
			public const int editText1 = 2131099667;

			// aapt resource value: 0x7f06002b
			public const int enlaceCredenciales = 2131099691;

			// aapt resource value: 0x7f060015
			public const int imageViewLocationIcon = 2131099669;

			// aapt resource value: 0x7f06000d
			public const int spinner1 = 2131099661;


			// aapt resource value: 0x7f06000f
			public const int spinner2 = 2131099663;


			// aapt resource value: 0x7f06000a
			public const int linearLayout1 = 2131099658;

			// aapt resource value: 0x7f060022
			public const int listViewInventarioLimpieza = 2131099682;

			// aapt resource value: 0x7f060025
			public const int listViewLimpieza = 2131099685;

			// aapt resource value: 0x7f060009
			public const int scrollView1 = 2131099657;

			// aapt resource value: 0x7f06000d
			public const int spinner1 = 2131099661;

			// aapt resource value: 0x7f06000f
			public const int spinner2 = 2131099663;

			// aapt resource value: 0x7f060011
			public const int spinner3 = 2131099665;

			// aapt resource value: 0x7f060011
			public const int spinner3 = 2131099665;


			// aapt resource value: 0x7f060005
			public const int spinnerEmpleadosLimpieza = 2131099653;

			// aapt resource value: 0x7f060003
			public const int spinnerHabitaciones = 2131099651;


			// aapt resource value: 0x7f060020
			public const int textView1 = 2131099680;

			// aapt resource value: 0x7f060024
			public const int textViewArticuloLimpieza = 2131099684;

			// aapt resource value: 0x7f060023
			public const int textViewArticuloMantenimiento = 2131099683;

			// aapt resource value: 0x7f060027
			public const int textViewBajaCantidad = 2131099687;

			// aapt resource value: 0x7f060014
			public const int textViewEncargadoHabitacion = 2131099668;

			// aapt resource value: 0x7f06001f
			public const int textViewEncargadoHabitacionDetalleMantenimiento = 2131099679;

			// aapt resource value: 0x7f06001b
			public const int textViewHabitacionDetalleMantenimiento = 2131099675;

			// aapt resource value: 0x7f060012
			public const int textViewHorario = 2131099666;

			// aapt resource value: 0x7f06001e
			public const int textViewHorarioDetalleMantenimiento = 2131099678;

			// aapt resource value: 0x7f060013
			public const int textViewHorarioHabitacion = 2131099667;

			// aapt resource value: 0x7f06000b
			public const int textView1 = 2131099659;

			// aapt resource value: 0x7f06000c
			public const int textView2 = 2131099660;

			// aapt resource value: 0x7f06000e
			public const int textView3 = 2131099662;


			// aapt resource value: 0x7f060025
			public const int textViewIncidencias = 2131099685;

			// aapt resource value: 0x7f060026
			public const int textViewLimpieza = 2131099686;

			// aapt resource value: 0x7f06001c
			public const int textViewObservacionesDetalleMantenimiento = 2131099676;

			// aapt resource value: 0x7f06000b
			public const int textView1 = 2131099659;

			// aapt resource value: 0x7f06000c
			public const int textView2 = 2131099660;

			// aapt resource value: 0x7f06000e
			public const int textView3 = 2131099662;


			// aapt resource value: 0x7f060010
			public const int textView4 = 2131099664;

			// aapt resource value: 0x7f060012
			public const int textView5 = 2131099666;

			// aapt resource value: 0x7f06001f
			public const int textViewEncargadoHabitacion = 2131099679;

			// aapt resource value: 0x7f06001d
			public const int textViewHorario = 2131099677;

			// aapt resource value: 0x7f06001e
			public const int textViewHorarioHabitacion = 2131099678;

			// aapt resource value: 0x7f06001b
			public const int textViewSituacion = 2131099675;


			// aapt resource value: 0x7f06000b
			public const int textViewUbicacion = 2131099659;

			// aapt resource value: 0x7f06001a
			public const int textViewUbicacionDetalleMantenimiento = 2131099674;

			// aapt resource value: 0x7f06001c
			public const int textViewSituacionHabitacion = 2131099676;

			// aapt resource value: 0x7f060017
			public const int textViewTamaño = 2131099671;

			// aapt resource value: 0x7f060018
			public const int textViewTamañoHabitacion = 2131099672;

			// aapt resource value: 0x7f060019
			public const int textViewTipo = 2131099673;

			// aapt resource value: 0x7f06001a
			public const int textViewTipoHabitacion = 2131099674;

			// aapt resource value: 0x7f060016
			public const int textViewUbicacion = 2131099670;


			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Id()
			{
			}
		}

		public partial class Layout
		{

			// aapt resource value: 0x7f030000
			public const int AltaOrdenLimpieza = 2130903040;


			// aapt resource value: 0x7f030001
			public const int AltaOrdenMantenimeinto = 2130903041;

			// aapt resource value: 0x7f030002
			public const int DetalleMantenimiento = 2130903042;

			// aapt resource value: 0x7f030003
			public const int GestionInventario = 2130903043;

			// aapt resource value: 0x7f030004
			public const int HomeAdmin = 2130903044;

			// aapt resource value: 0x7f030005
			public const int InventarioLimpieza = 2130903045;

			// aapt resource value: 0x7f030006
			public const int Limpieza = 2130903046;

			// aapt resource value: 0x7f030007
			public const int Login = 2130903047;

			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;

			// aapt resource value: 0x7f030009
			public const int Registro = 2130903049;


			// aapt resource value: 0x7f030001
			public const int AltaOrdenMantenimeinto = 2130903041;

			// aapt resource value: 0x7f030002

			public const int DetalleHabitacion = 2130903042;

			// aapt resource value: 0x7f030003
			public const int DetalleMantenimiento = 2130903043;

			// aapt resource value: 0x7f030004
			public const int GestionInventario = 2130903044;

			// aapt resource value: 0x7f030005
			public const int HomeAdmin = 2130903045;

			// aapt resource value: 0x7f030006
			public const int InventarioLimpieza = 2130903046;

			// aapt resource value: 0x7f030007
			public const int Limpieza = 2130903047;

			// aapt resource value: 0x7f030008
			public const int Login = 2130903048;

			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;

			// aapt resource value: 0x7f03000a
			public const int Registro = 2130903050;


			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Layout()
			{
			}
		}

		public partial class String
		{

			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;

			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;

			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
